# -*- coding: utf-8 -*-
"""vetores.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y3bcyU9I4UjG0_5W1miIhjrhFM3WQja_

# Introdução ao Python

## Exemplos de array
"""

import numpy as np

notas =  []
media = 0
soma = 0
contaElementos = 0

for n in range(0,5,1):
  notas.append(float(input("Entre com a nota do aluno: ")))

print(notas[1])

for x in range(0,5,1):
  soma += notas[x]
  contaElementos+=1

media = soma/contaElementos
print("A media das notas -->",media)

#utilizando numpy
#convert list to numpy array
x = np.array(notas)
print("A media com numpy -->", np.mean(notas))
print("A media com numpy array -->", x.mean())
print("A soma do vetor com numpy -->", np.sum(notas), " - ", x.sum())
print("O maior elemento -->", np.max(notas), " - ", x.max())
print("O menor elemento -->", np.min(notas), " - ", x.min())

"""Faça um programa que leia 10 números inteiros, armazene-os em um array e depois percorra o array somando todos os valores. No final, mostre a soma."""

import numpy as np
n1 =  []

for i in range(10):
  n1.append(int(input(f"Entre com o {i + 1}º número: ")))
i = np.array(n1)
print("A soma: ", np.sum(n1))

"""Faça um programa que leia 5 números inteiros, armazene-os em um array e some todos os valores cujo índice seja par. Mostre a soma no final"""

import numpy as np
n1 = []
soma = 0
for i in range(5):
   n1.append(int(input(f"Informe o {i + 1}º número inteiro: "))) 
i = np.array(n1)

for s in i:
   if s % 2 == 0:
     soma += s
print("A soma: ", np.sum(soma))

"""Faça um programa que leia 5 números inteiros, armazene-os em um array e exiba-os em ordem inversa."""

import numpy as np
n1 = []

for i in range(5):
   n1.append(int(input(f"Informe o {i + 1}º número inteiro: "))) 
   n1.reverse()
i = np.array(n1)

print(i)

"""Faça um programa que leia 5 números inteiros, armazene-os em um array e mostre a soma de todos os números pares e a soma de todos os números ímpares."""

import numpy as np
n5 = []
par = 0
impar = 0

for x in range(5):
   n5.append(int(input(f"Informe o {x + 1}º número inteiro: "))) 
x = np.array(n5)

for s in x:
   if s % 2 == 0:
    par += s
   elif s % 2 != 0:
    impar += s

print("Soma de números pares: ", par)
print("Soma de números ímpares: ", impar)